# Deleted port settings.
# ports:
#   - port: 5173
#     onOpen: open-browser
#   - port: 5432
#     onOpen: ignore
#   - port: 5555
#     onOpen: open-browser

image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: |
      export HMR_HOST=`gp url 5173`
      npm run dev
  - command: npx prisma studio
    env:
      DATABASE_URL: postgres://gitpod@localhost/todos

ports:
  - port: 5173
    onOpen: open-browser
  - port: 5555
    onOpen: open-browser

vscode:
  extensions:
    - svelte.svelte-vscode
    - Prisma.prisma

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
